Vegan Zombie Crop Apocalypse: UDetectionComponent Class Reference
UDetectionComponent Class Reference
#include <DetectionComponent.h>
Public Member Functions
UDetectionComponent ()
virtual void TickComponent (float DeltaTime, ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
void AddVegetable (AActor *Actor)
int GetCount (const FName &Vegetable)
TMap< FName, int > & GetMap ()
FString StringifyMap (const TMap< FName, int > &map_)
TSet< TWeakObjectPtr< AActor > > & GetVegetableSet ()
void Cleanup ()
Public Attributes
TMap< FName, int > map
Protected Member Functions
virtual void BeginPlay () override
Private Attributes
TSet< TWeakObjectPtr< AActor > > VegetableSet
Detailed Description
Definition at line 11 of file DetectionComponent.h.
Constructor & Destructor Documentation
UDetectionComponent()
UDetectionComponent::UDetectionComponent ()
Definition at line 7 of file DetectionComponent.cpp.
{
    // Set this component to be initialized when the game starts, and to be ticked every frame.  You can turn these features
    // off to improve performance if you don't need them.
    PrimaryComponentTick.bCanEverTick = true;
    // ...
}
Member Function Documentation
AddVegetable()
void UDetectionComponent::AddVegetable (AActor * Actor)
Definition at line 35 of file DetectionComponent.cpp.
{
    if(!Actor->ActorHasTag("Vegetable")) return;
    bool bAlreadyInSet = false;
    //checks whether an element is already in the set and sets the bool to true or else adds the element to the set
    VegetableSet.Add(Actor, &bAlreadyInSet);
    if(bAlreadyInSet == false)
    {
        UE_LOG(LogTemp, Warning, TEXT("Adding..."));
        UStaticMeshComponent* StaticMesh = Actor->FindComponentByClass<UStaticMeshComponent>();
        if(StaticMesh!=nullptr && !StaticMesh->ComponentTags.IsEmpty())
        {
            const FName& Tag = StaticMesh->ComponentTags[0];
            UE_LOG(LogTemp, Display, TEXT("%s"), *StaticMesh->ComponentTags[0].ToString());
            if(map.Contains(Tag))++map[Tag];
            else map.Add(Tag, 1);
        }
    }
    Cleanup();
}
BeginPlay()
void UDetectionComponent::BeginPlay () override protected virtual
Definition at line 18 of file DetectionComponent.cpp.
{
    Super::BeginPlay();
    // ...
}
Cleanup()
void UDetectionComponent::Cleanup ()
Definition at line 56 of file DetectionComponent.cpp.
{
    if(VegetableSet.Num() > 4)
    {
        TArray<TWeakObjectPtr<AActor>> ToRemove;
        //Iterating over the set and adding invalid object references to the remove array to ensure iterator stability
        //Don't want to remove objects as we iterate over a container to not mess up the iterators
        for(auto& item : VegetableSet)
        {
            if(!item.IsValid())ToRemove.Add(item);
        }
        for(auto& item : ToRemove)
        {
            VegetableSet.Remove(item);
        }
    }
}
Referenced by AddVegetable(), and URecipebuilder::UpdateRecipeUI().
GetCount()
int UDetectionComponent::GetCount (const FName & Vegetable)
Definition at line 76 of file DetectionComponent.cpp.
{
    if(map.Contains(Vegetable))
    {
        return map[Vegetable];
    }
    return 0;
}
GetMap()
TMap< FName, int > & UDetectionComponent::GetMap ()
Definition at line 99 of file DetectionComponent.cpp.
{
    return map;
}
Referenced by URecipebuilder::UpdateRecipeUI().
GetVegetableSet()
TSet< TWeakObjectPtr< AActor > > & UDetectionComponent::GetVegetableSet ()
Definition at line 104 of file DetectionComponent.cpp.
{
    return VegetableSet;
}
Referenced by URecipebuilder::UpdateRecipeUI().
StringifyMap()
FString UDetectionComponent::StringifyMap (const TMap< FName, int > & map_)
Definition at line 86 of file DetectionComponent.cpp.
{
    FString out;
    bool bFirst = true;
    for (const auto &pair : map_) {
        if (bFirst)
            bFirst = false;
        else
            out += "; ";
        out += pair.Key.ToString() + TEXT(" => ") + FString::FromInt(pair.Value);
    }
    return out;
}
TickComponent()
void UDetectionComponent::TickComponent (float DeltaTime, ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
Definition at line 28 of file DetectionComponent.cpp.
{
    Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
    // ...
}
Member Data Documentation
map
TMap<FName, int> UDetectionComponent::map
Definition at line 27 of file DetectionComponent.h.
Referenced by AddVegetable(), GetCount(), and GetMap().
VegetableSet
TSet<TWeakObjectPtr<AActor> > UDetectionComponent::VegetableSet private
Definition at line 49 of file DetectionComponent.h.
Referenced by AddVegetable(), Cleanup(), and GetVegetableSet().
The documentation for this class was generated from the following files:
D:/code/vegan-harvest/UMPGorePack/Source/UMPGorePack/DetectionComponent.h
D:/code/vegan-harvest/UMPGorePack/Source/UMPGorePack/DetectionComponent.cpp